### ISSUE TITLE
Enhancement: CLI command to check CWE memberships

### ISSUE THREAD

**Issue by bfedoronchuk** [lirantal/cwe-sdk#2]
**Is your feature request related to a problem? Please describe.**
Sometimes CWE is a member of other enumerations. It will be helpful to obtain the related categories in order to get the other weakness descriptions.

**Describe the solution you'd like**
For example, we run the command 
`> cwe-sdk memberships 778`
 and it will output "A10: 2017 Insufficient Logging & Monitoring". 
Here is CWE: https://cwe.mitre.org/data/definitions/778.html

**Comment by bfedoronchuk** [comment]
Also, such flags could be helpful:
`> cwe-sdk memberships <id> --owasp/--owasp-api/--fortify-vulncat/--all`

**Comment by lirantal** [comment]
Yep, that would be a great addition!
Minor note - this is the SDK repo, and if you're referring to the CLI repository then that's over at https://github.com/lirantal/cwe-tool

**Comment by lirantal** [comment]
FYI this repo migrated to OWASP at https://github.com/OWASP/cwe-sdk-javascript/issues/1
